services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 5s
      timeout: 60s
      retries: 5